name: Deploy Backend to Railway

on:
  push:
    branches:
      - master
    paths:
      - "backend/**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Instalar Railway CLI
        run: curl -fsSL https://railway.app/install.sh | sh

      - name: Autenticarse en Railway
        run: railway login --token ${{ secrets.RAILWAY_API_TOKEN }}

      - name: Desplegar Backend
        run: |
          cd backend
          railway up
